import {images} from '../assets/images';
import {ScreenNames} from '../constants/strings';

export const alphabetData = [
  {
    image: images.alphabets.aligator,
    name: 'Lesson 1 A',
    letter: 'A',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/a_vbdrdy.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Apple', image: images.letterA.apple},
      {name: 'Alligator', image: images.letterA.aligator},
      {name: 'Axe', image: images.letterA.axe},
      {name: 'Airplane', image: images.letterA.airplane},
      {name: 'Arrow', image: images.letterA.arrow},
      {name: 'Ape', image: images.letterA.ape},
      {name: 'Arm', image: images.letterA.arm},
      {name: 'Angel', image: images.letterA.angel},
      {name: 'Aunt', image: images.letterA.aunt},
      {name: 'Ambulance', image: images.letterA.ambulance},
    ],
  },
  {
    image: images.alphabets.bear,
    name: 'Lesson 2 B',
    letter: 'B',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/b_kyrt9a.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Bat', image: images.letterB.bat},
      {name: 'Ball', image: images.letterB.ball},
      {name: 'Bus', image: images.letterB.bus},
      {name: 'Bread', image: images.letterB.bread},
      {name: 'Brain', image: images.letterB.brain},
      {name: 'Bag', image: images.letterB.bag},
      {name: 'Bunny', image: images.letterB.bunny},
      {name: 'Banana', image: images.letterB.banana},
      {name: 'Bear', image: images.letterB.bear},
      {name: 'Ballon', image: images.letterB.ballon},
      {name: 'Baby', image: images.letterB.baby},
      {name: 'Book', image: images.letterB.book},
    ],
  },
  {
    image: images.alphabets.cat,
    name: 'Lesson 3 C',
    letter: 'C',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/c_p8a1w3.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Cat', image: images.letterC.cat},
      {name: 'Car', image: images.letterC.car},
      {name: 'Carrot', image: images.letterC.carrot},
      {name: 'Clock', image: images.letterC.clock},
      {name: 'Cow', image: images.letterC.cow},
      {name: 'Cap', image: images.letterC.cap},
      {name: 'Cake', image: images.letterC.cake},
      {name: 'Clouds', image: images.letterC.clouds},
      {name: 'Comb', image: images.letterC.comb},
    ],
  },
  {
    image: images.alphabets.dog,
    name: 'Lesson 4 D',
    letter: 'D',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/d_dnzmps.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Duck', image: images.letterD.duck},
      {name: 'Door', image: images.letterD.door},
      {name: 'Deer', image: images.letterD.deer},
      {name: 'Dog', image: images.letterD.dog},
      {name: 'Dolphin', image: images.letterD.dolphin},
      {name: 'Dress', image: images.letterD.dress},
      {name: 'Drum', image: images.letterD.drum},
      {name: 'Dragon', image: images.letterD.dragon},
    ],
  },
  {
    image: images.alphabets.elephant,
    name: 'Lesson 5 E',
    letter: 'E',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/e_aewktw.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Eagle', image: images.letterE.eagle},
      {name: 'Ear', image: images.letterE.ear},
      {name: 'Earth', image: images.letterE.earth},
      {name: 'Egg', image: images.letterE.egg},
      {name: 'Elephant', image: images.letterE.elephant},
      {name: 'Elf', image: images.letterE.elf},
      {name: 'Eye', image: images.letterE.eye},
    ],
  },
  {
    image: images.alphabets.fox,
    name: 'Lesson 6 F',
    letter: 'F',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/f_xwtzfr.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Fan', image: images.letterF.fan},
      {name: 'Feet', image: images.letterF.feet},
      {name: 'Flag', image: images.letterF.flag},
      {name: 'FLower', image: images.letterF.flower},
      {name: 'Fork', image: images.letterF.fork},
      {name: 'Frog', image: images.letterF.frog},
    ],
  },
  {
    image: images.alphabets.girafe,
    name: 'Lesson 7 G',
    letter: 'G',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/g_lr8ajo.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Gate', image: images.letterG.gate},
      {name: 'Giraffe', image: images.letterG.giraffe},
      {name: 'Girl', image: images.letterG.girl},
      {name: 'Glasses', image: images.letterG.glasses},
      {name: 'Goat', image: images.letterG.goat},
      {name: 'Goose', image: images.letterG.goose},
      {name: 'Grapes', image: images.letterG.grape},
    ],
  },
  {
    image: images.alphabets.horse,
    letter: 'H',
    name: 'Lesson 8 H',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/h_yitjyo.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Hammer', image: images.letterH.hammer},
      {name: 'Hat', image: images.letterH.hat},
      {name: 'Hen', image: images.letterH.hen},
      {name: 'Honey', image: images.letterH.honey},
      {name: 'Horse', image: images.letterH.horse},
      {name: 'House', image: images.letterH.house},
    ],
  },
  {
    image: images.alphabets.iguana,
    name: 'Lesson 9 I',
    letter: 'I',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/i_jp67jl.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Ice', image: images.letterI.ice},
      {name: 'Ice Cream', image: images.letterI.iceCream},
      {name: 'Igloo', image: images.letterI.igloo},
      {name: 'Ink', image: images.letterI.ink},
    ],
  },
  {
    image: images.alphabets.jaguar,
    letter: 'J',
    name: 'Lesson 10 J',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253766/alphabets/j_xx2ycs.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Jackal', image: images.letterJ.jackal},
      {name: 'Jaguar', image: images.letterJ.jaguar},
      {name: 'Jar', image: images.letterJ.jar},
      {name: 'Jeep', image: images.letterJ.jeep},
      {name: 'Jelly', image: images.letterJ.jelly},
      {name: 'Jet', image: images.letterJ.jet},
      {name: 'Jug', image: images.letterJ.jug},
    ],
  },
  {
    image: images.alphabets.kangroo,
    letter: 'K',
    name: 'Lesson 11 K',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253766/alphabets/k_k9bvqs.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Kangaroo', image: images.letterK.kangaroo},
      {name: 'Kids', image: images.letterK.kid},
      {name: 'Kites', image: images.letterK.kite},
      {name: 'Kitten', image: images.letterK.kitten},
      {name: 'Knife', image: images.letterK.knife},
    ],
  },
  {
    image: images.alphabets.lion,
    letter: 'L',
    name: 'Lesson 12 L',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253766/alphabets/l_zfugzq.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Ladder', image: images.letterL.ladder},
      {name: 'Lamp', image: images.letterL.lamp},
      {name: 'Leaf', image: images.letterL.leaf},
      {name: 'Leopard', image: images.letterL.leopard},
      {name: 'Log', image: images.letterL.log},
      {name: 'Lion', image: images.letterL.lion},
    ],
  },
  {
    image: images.alphabets.monkey,
    letter: 'M',
    name: 'Lesson 13 M',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/m_ipjn8g.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Mango', image: images.letterM.mango},
      {name: 'Mat', image: images.letterM.mat},
      {name: 'Monkey', image: images.letterM.monkey},
      {name: 'Moon', image: images.letterM.moon},
      {name: 'Mug', image: images.letterM.mug},
    ],
  },
  {
    image: images.alphabets.nshark,
    letter: 'N',
    name: 'Lesson 14 N',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/n_ch0k3r.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Nail', image: images.letterN.nail},
      {name: 'Necklace', image: images.letterN.necklace},
      {name: 'Needle', image: images.letterN.needle},
      {name: 'Nose', image: images.letterN.nose},
      {name: 'Nurse', image: images.letterN.nurse},
    ],
  },
  {
    image: images.alphabets.octopus,
    letter: 'O',
    name: 'Lesson 15 O',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/o_shfojc.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Owl', image: images.letterO.owl},
      {name: 'Ox', image: images.letterO.ox},
      {name: 'Ostrich', image: images.letterO.ostrich},
      {name: 'Oven', image: images.letterO.oven},
      {name: 'Orange', image: images.letterO.orange},
      {name: 'Oats', image: images.letterO.oats},
    ],
  },
  {
    image: images.alphabets.penguin,
    letter: 'P',
    name: 'Lesson 16 P',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/p_iy184f.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Pan', image: images.letterP.pan},
      {name: 'Panda', image: images.letterP.panda},
      {name: 'Parrot', image: images.letterP.parrot},
      {name: 'Pear', image: images.letterP.pear},
      {name: 'Pencil', image: images.letterP.pencil},
      {name: 'Penguin', image: images.letterP.penguin},
    ],
  },
  {
    image: images.alphabets.quirl,
    letter: 'Q',
    name: 'Lesson 17 Q',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/q_btlcnf.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Quack', image: images.letterQ.quack},
      {name: 'Queen', image: images.letterQ.queen},
      {name: 'Queue', image: images.letterQ.queue},
      {name: 'Quilt', image: images.letterQ.quilt},
    ],
  },
  {
    image: images.alphabets.rabit,
    letter: 'R',
    name: 'Lesson 18 R',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253764/alphabets/r_znqtty.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Rabbit', image: images.letterR.rabbit},
      {name: 'Ring', image: images.letterR.ring},
      {name: 'Rock', image: images.letterR.rock},
      {name: 'Rocket', image: images.letterR.rocket},
      {name: 'Rose', image: images.letterR.rose},
    ],
  },
  {
    image: images.alphabets.snake,
    letter: 'S',
    name: 'Lesson 19 S',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253765/alphabets/s_lvyh1z.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Salt', image: images.letterS.salt},
      {name: 'Sand', image: images.letterS.sand},
      {name: 'School', image: images.letterS.school},
      {name: 'Sea', image: images.letterS.sea},
      {name: 'Shark', image: images.letterS.shark},
      {name: 'Sheep', image: images.letterS.sheep},
      {name: 'Snake', image: images.letterS.snake},
    ],
  },
  {
    image: images.alphabets.tiger,
    letter: 'T',
    name: 'Lesson 20 T',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/t_udt76o.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Tank', image: images.letterT.tank},
      {name: 'Tent', image: images.letterT.tent},
      {name: 'Tiger', image: images.letterT.tiger},
      {name: 'Tomato', image: images.letterT.tomato},
      {name: 'Tractor', image: images.letterT.tractor},
      {name: 'Tree', image: images.letterT.tree},
      {name: 'Turtle', image: images.letterT.turtle},
    ],
  },
  {
    image: images.alphabets.unicorn,
    letter: 'U',
    name: 'Lesson 21 U',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/u_sba8os.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Umbrella', image: images.letterU.umbrella},
      {name: 'Uncle', image: images.letterU.uncle},
      {name: 'Unicorn', image: images.letterU.unicorn},
    ],
  },
  {
    image: images.alphabets.vulture,
    letter: 'V',
    name: 'Lesson 22 V',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/v_wdj25c.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Van', image: images.letterV.van},
      {name: 'Vase', image: images.letterV.vase},
      {name: 'Village', image: images.letterV.village},
      {name: 'Violin', image: images.letterV.violin},
      {name: 'Vulture', image: images.letterV.vulture},
    ],
  },
  {
    image: images.alphabets.whale,
    letter: 'W',
    name: 'Lesson 23 W',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/w_wl6fml.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Wall', image: images.letterW.wall},
      {name: 'Watermelon', image: images.letterW.watermelon},
      {name: 'Well', image: images.letterW.well},
      {name: 'Whale', image: images.letterW.whale},
      {name: 'Wolf', image: images.letterW.wolf},
      {name: 'Worm', image: images.letterW.worm},
    ],
  },
  {
    image: images.alphabets.xrayfish,
    letter: 'X',
    name: 'Lesson 24 X',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/x_dhph57.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'X-Ray', image: images.letterX.xray},
      {name: 'Xylophone', image: images.letterX.xylophone},
    ],
  },
  {
    image: images.alphabets.yak,
    letter: 'y',
    name: 'Lesson 25 Y',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/y_v065lo.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Yacht', image: images.letterY.yacht},
      {name: 'Yak', image: images.letterY.yak},
      {name: 'Yo-Yo', image: images.letterY.yoyo},
      {name: 'Yolk', image: images.letterY.yolk},
    ],
  },
  {
    image: images.alphabets.zebra,
    letter: 'Z',
    name: 'Lesson 26 Z',
    soundFile:
      'https://res.cloudinary.com/dtpvy8gil/video/upload/v1732253767/alphabets/z_c8chtr.wav',
    screen: ScreenNames.alphabetExerciseMainScreen,
    progress: 0,
    exercises: [
      {name: 'Zebra', image: images.letterZ.zebra},
      {name: 'Zipper', image: images.letterZ.zipper},
      {name: 'Zoo', image: images.letterZ.zoo},
    ],
  },
];
